spring.application.name=funilaria

# URL de conexão (localhost porque o Docker mapeou a porta 5432 para sua máquina)
spring.datasource.url=jdbc:postgresql://localhost:5432/meu_banco_de_dados
spring.datasource.username=usuario_dev
spring.datasource.password=senha_dev
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do Hibernate / JPA
# "update" cria as tabelas automaticamente baseado nas suas classes @Entity
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
